### ISSUE TITLE
Chat does not show what you have said with chat_translator enabled

### ISSUE THREAD

**Issue by dontfwiththestream** [Droog71/chat_translator#1]
Expected behavior: 

A client (Bob) types "hello" into chat

The same client (Bob) sees:
 <Bob> hello
in the chat window 
This is the behavior seen when running the game without chat translate

Actual Behavior:

A client (Bob) types "hello" into chat

The same client (Bob) sees nothing in the chat window, as if he hadn't sent anything to chat at all

Steps to reproduce:

install chat_translator and type anything into chat.

**Comment by Droog71** [comment]
This issue has been fixed.
Thanks for the bug report!
https://github.com/Droog71/chat_translator/commit/7081c3bc04db24698512c852286864b008d1346e

**Comment by dontfwiththestream** [comment]
thanks for the rapid response! Absolutely awesome mod, this saves me constantly having to retype chat into translate in a second window just to communicate
