### ISSUE TITLE
translator occasionally causes repeated words in chat

### ISSUE THREAD

**Issue by dontfwiththestream** [Droog71/chat_translator#2]
Ok, this is a little hard to describe, and i am not sure how to give you more information. I will gladly do whatever is needed to help you identify the issue if you instruct me how to, but here goes:

I have several people on the server speaking different languages. Occasionally, it will repeat the message sent to chat. In example:

player 1 says "hello" in $language
the translated message will repeat "hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello hello " in chat

this leads to a very spammy chat experience

**Comment by Droog71** [comment]
Was this occuring before this fix was implemented?
https://github.com/Droog71/chat_translator/issues/1

**Comment by dontfwiththestream** [comment]
I don't remember seeing it before that, but I didn't have chat_translator installed very long before opening that issue.

**Comment by Droog71** [comment]
> I don't remember seeing it before that, but I didn't have chat_translator installed very long before opening that issue.

Ok. Just a couple more questions so I can try to figure out what is going on.
Is player 1 typing this message in the same language they have selected in the Minetest options menu?
For whom is the message repeated as you've described? Everyone in the server?
Is the message repeated infinitely or roughly the number of times you have shown here?
Have you seen any errors related to LIbreTranslate in the server logs when this is happening?

**Comment by Droog71** [comment]
I did some testing today and was unable to reproduce this bug.
Using 3 minetest clients. One hosting a server, two connected to the server, all three selecting different languages.
Tiling the windows, I cycled through them, sending a bunch of messages. Some in English, some in Spanish.
I tried spamming the chat, rapidly sending messages. I was never able to reproduce the issue.

**Comment by dontfwiththestream** [comment]
I will do some looking through the logs tomorrow, sorry I haven't had the chance yet. Have been stuck at work

**Comment by Droog71** [comment]
Unable to reproduce.
