### ISSUE TITLE
'Translator' puts the word "english" (without "") to the In-Game Chat, sometimes, seems to be due to a failed translation(?)

### ISSUE THREAD

**Issue by JohannesPaulHoffmann** [Droog71/chat_translator#6]
Hi,

We get the word "english" (without "") printed in the In-Game Chat, for example, where I know it from in particular, when the word "ahoj" gets used (seems to be from 'Czech' → English(?)).

Regards,
Johannes

**Comment by Droog71** [comment]
> Hi,
> 
> We get the word "english" (without "") printed in the In-Game Chat, for example, where I know it from in particular, when the word "ahoj" gets used (seems to be from 'Czech' → English(?)).
> 
> Regards, Johannes

Yes, LibreTranslate cannot translate this word. That is an issue with LibreTranslate. I cannot fix it.
![Screenshot at 2023-12-18 00-00-29](https://github.com/Droog71/chat_translator/assets/6352433/5dd742e5-5998-4dec-908f-71aa6daa1d22)
